services:
  flask:
    build: ./flask
    ports:
      - "5050:5000"
    depends_on:
      - postgres
    # volumes:
    # - ./mlruns:/app/mlruns  # <== mount host's mlruns into container
    volumes:
    - model_cache:/root/.cache/torch  # Mount the cache for reused model weights

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - flask
      - postgres
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # React app served on port 3000

volumes:
  model_cache:
